version: "3"
services:
  latex:
    build:
      context: ./images/latex
      dockerfile: Dockerfile
    container_name: "latex"
    working_dir: /wk/self-assessment
    volumes:
      - ${WORKSPACE}/self-assessment:/wk/self-assessment
  go:
    build:
      context: ./images/go
      dockerfile: Dockerfile
    container_name: "golang"
    working_dir: /go/src/github.com/jmuldoon/go-keychain
    volumes:
      - ${GOPATH}:/go
