version: "3.5"
services:
  latex:
    build:
      context: ./images/latex
      dockerfile: Dockerfile
    container_name: "latex"
    working_dir: /wk/self-assessment
    volumes:
      - ${WORKSPACE}/self-assessment:/wk/self-assessment
  go:
    build:
      context: ./images/go
      dockerfile: Dockerfile
    container_name: "golang"
    working_dir: /go/src/github.com/jmuldoon/go-keychain
    volumes:
      - ${GOPATH}:/go
  python:
    build:
      context: ./images/python
      dockerfile: Dockerfile
    container_name: "python"
    working_dir: /wk/run-n-player-game
    volumes:
      - ${WORKSPACE}/python/run-n-player-game:/wk/run-n-player-game
